import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import DemoTable from '../components/DemoTable';
import 'antd/dist/antd.css';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [singleData, setSingleData] = useState(null);
  const updateSingleData = (data) => setSingleData(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <DemoTable updateSingleData={updateSingleData} />
        <div className="single-data">
          <p>Name: {singleData ? singleData.name : ''}</p>
          <p>Age: {singleData ? singleData.age : ''} </p>
          <p>
            Address: {singleData ? singleData.address : ''}
          </p>
        </div>
      </div>
    </div>
  );
}
